/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const isDark: typeof import('./src/composables/dark')['isDark']
  const toggleDark: typeof import('./src/composables/dark')['toggleDark']
}
